config:
  ORG_MULTI_TENANT: ''
  POSTGRES_DB_URI: '${HOOP_SELF_HOSTED_ENJOEI_POSTGRES_DB_URI}'
  PGREST_ROLE: 'hoop_apiuser_enjoei'
  API_URL: 'https://enjoei.hoop.dev'
  IDP_URI: "https://${HOOP_SELF_HOSTED_ENJOEI_IDP_CLIENT_ID}:${HOOP_SELF_HOSTED_ENJOEI_IDP_CLIENT_SECRET}@oauth.id.jumpcloud.com/"
  IDP_AUDIENCE: ''
  ASK_AI_CREDENTIALS: '${HOOP_SELF_HOSTED_ENJOEI_ASK_AI_CREDENTIALS}'
  GOOGLE_APPLICATION_CREDENTIALS_JSON: '${GOOGLE_APPLICATION_CREDENTIALS_JSON}'
  WEBHOOK_APPKEY: '${HOOP_SELF_HOSTED_ENJOEI_WEBHOOK_APPKEY}'
  PYROSCOPE_AUTH_TOKEN: ''
  PYROSCOPE_INGEST_URL: ''
  ADMIN_USERNAME: 'RunOps - Admin'
  PLUGIN_AUDIT_PATH: '/opt/hoop/sessions'
  PLUGIN_INDEX_PATH: '/opt/hoop/sessions/indexes'
  PLUGIN_REGISTRY_URL: 'https://pluginregistry.s3.amazonaws.com/packages.json'
  MAGIC_BELL_API_KEY: ''
  MAGIC_BELL_API_SECRET: ''

persistence:
  # -- Use persistent volume for write ahead log sessions
  enabled: true
  storageClassName: gp2

  # -- Size of persistent volume claim
  size: 10Gi

ingressApi:
  enabled: true
  host: enjoei.hoop.dev
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:200074533906:certificate/8bd787af-787a-47fd-8010-1cef0c28228d
    alb.ingress.kubernetes.io/group.name: enjoeigroup
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip

ingressGrpc:
  enabled: true
  host: enjoei.hoop.dev
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:200074533906:certificate/8bd787af-787a-47fd-8010-1cef0c28228d
    alb.ingress.kubernetes.io/group.name: enjoeigroup
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 8443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

# -- CPU/Memory resource requests/limits
resources:
  gw:
    limits:
      cpu: 2048m
      memory: 2Gi
    requests:
      cpu: 512m
      memory: 2Gi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-east-1a
