{{- if .Values.rdpService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: hoopgateway-pgproxy
  labels:
    app: hoopgateway-pgproxy
  {{- with .Values.rdpService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.rdpService.type | default "LoadBalancer" }}
  ports:
    - name: pg
      port: {{ .Values.rdpService.port | default 13389 }}
      targetPort: 15432
      protocol: TCP
      {{- if and (eq (.Values.rdpService.type | default "LoadBalancer") "NodePort") .Values.rdpService.nodePort }}
      nodePort: {{ .Values.rdpService.nodePort }}
      {{- end }}
  selector:
    app: hoopgateway
{{- end }}