apiVersion: v1
kind: Secret
metadata:
  name: agent-config
type: Opaque
stringData:
  HOOP_KEY: '{{ required "config.HOOP_KEY is required" .Values.config.HOOP_KEY }}'
  LOG_ENCODING: '{{ .Values.config.LOG_ENCODING | default "json" }}'
  LOG_LEVEL: '{{ .Values.config.LOG_LEVEL | default "info" }}'
  LOG_GRPC: '{{ .Values.config.LOG_GRPC | default "0" }}'
  GODEBUG: 'http2debug={{ .Values.config.LOG_GRPC | default "0" }}'
  HOOP_GATEWAY_URL: '{{ .Values.config.HOOP_GATEWAY_URL | default "" }}'